linuxwacom/xf86-input-wacom

src/wcmValidateDevice.c
Feature flags are used by the driver to determine if a particular device
needs special treatment. The devices usually work "okay" without these
flags set, but missing flags can result in some features not working
or not working as expected. For instance, the touch ring on the Bluetooth
interface of the 2nd-gen Intuos Pro does not work at the moment because
the WCM_RING feature is missing. It also gains the WCM_ROTATION flag.
All other devices added gain the WCM_LCD flag, as well as the WCM_ROTATION
flag if the device supports pen rotation.
Signed-off-by: Aaron Armstrong Skomra <aaron.skomra@wacom.com>
=> Add feature flags for several missing tablets

src/wcmUSB.c
The Surface Go sends `ABS_MISC` events from the kernel that confuse our driver. This pull request ensures that the generic protocol is always used for non-Wacom devices and that the driver properly handles usually-non-generic data from a generic tablet.
Ref: https://github.com/linuxwacom/xf86-input-wacom/issues/52/
=> Fix issues with Microsoft Surface Go tablet

man/wacom.man, man/xsetwacom.man, src/wcmCommon.c, src/wcmUSB.c, src/wcmValidateDevice.c, src/wcmXCommand.c, src/xf86WacomDefs.h
The "CursorProximity" setting was previously only available to puck devices and allowed users to define a distance at which the driver would force the tool out of prox. This was necessary to make using pucks more comfortable, since removing the puck from hardware prox may require it to be lifted a very large distance.
This pull request brings the same setting over to stylus devices that are used in relative mode. Effectively moving the pointer in relative mode with the stylus can be difficult without a similar way to limit the prox distance in software (especially with newer tablets that have very high hover heights).
Adding this fetaure also ensures that the driver does not accidentally treat the pen as making a large relative move when the pen is lifted into its "in-range" zone (where …
=> Allow stylus devices to have "CursorProximity" effect in relative mode

tools/tools-shared.c
The read_data() function is given a "min_len" number of bytes to read
to ensure that a complete data structure is read, regardless of garbage
that may be on the line. When garbage is present, however, it can
potentially overflow the buffer.
The function already has code to memmove the good data over garbage and
perform re-reads until "min_len" bytes of good data are available. All
we need to do to avoid the buffer overflow is ensure that the maximum
number of bytes we read() in one call is no more than the number of
bytes free at the end of the buffer.
Ref: https://github.com/linuxwacom/xf86-input-wacom/issues/86
Fixes: 3546d8ab1b ("tools: add isdv4-serial-debugger test program")
=> tools: Fix potential buffer overflow when reading from serial tablet

src/wcmUSB.c, src/xf86WacomDefs.h
AES sensors use protocol 5 since they send ABS_MISC events which contain
information about the tool type in use. The tool type information sent
by AES sensors does not match that used by EMR sensors, however. In
particular, it is not possible to extract stylus/eraser/puck information
from the ID.
The driver would normally never try to extract this information, but the
problem was highlighed when a bug in the kernel would cause the device ID
to be reported twice: once in a packet alongside a BTN_TOOL_* event (fine)
and a second time in a packet without such an event (causing the driver
to try to figure it out from the ID instead).
This commit adds detection for AES pen IDs and does not try to extract
such information if an AES pen is in use.
Ref: …
=> Ignore ABS_MISC as a source of device type information for AES pens

src/wcmUSB.c, src/wcmValidateDevice.c
A new PID is in use for repaired MobileStudio Pro devices. Add it to the
various device properties lists.
=> Recognize new MobileStudio Pro PID

src/wcmValidateDevice.c
Kernels older than 2.6.38 do not report INPUT_PROP_DIRECT
Signed-off-by: Ping Cheng <ping.cheng@wacom.com>
=> Support new Cintiqs for older kernels

.travis.yml
Hi,
I had added ppc64le support on travis ci and looks like its been successfully added. I believe it is ready for the final review and merge.
The travis-ci build logs can be verified from the link below.
https://www.travis-ci.com/github/kishorkunal-raj/xf86-input-wacom/builds/185558986
Please have a look.
Thanks!!"
=> Adding ppc64le architecture to support on travis-ci

.travis.yml
https://docs.travis-ci.com/user/multi-cpu-architectures/ says that "explicitly
included builds inherit the first value in an array" and the example there
matches our configuration.
Moving ppc64le to after amd64 means the coverity job we have is now (again)
run on amd64 only, fixing the current test case failures - Coverity doesn't
support ppc64le.
cc @kishorkunal-raj 
Note: don't think we can actually test this until we merge, the coverity job is on a schedule
=> travis CI: order ppc64le after amd64

src/wcmUSB.c, src/xf86WacomDefs.h
We occasionally see warnings in the Xorg log about the driver exceeding the event queue. This usually happens in corner cases (e.g. heavy multitouch use, cleaning of devices while they're on, etc.) but its easy enough to avoid the negative consequences that can happen when triggered.
=> Increase size of kernel event queue

conf/wacom.rules
*(Hope you don't mind that I swiped the text from your similar libwacom commit Peter :))*
Summary: we expect add, change or remove but kernel 4.12 added bind and
unbind. These events were previously discarded by udevd. Our rules should
handle any event *but* remove, so update as suggested in the announce email
linked below.
For a longer explanation, see the system 247rc2 announcement
https://lists.freedesktop.org/archives/systemd-devel/2020-November/045570.html
=> tools: update rules to handle bind/unbind events

src/wcmCommon.c
Always stop pointer movement when a panscroll button is pressed in
relative mode, instead of only when the pen is down. This keeps the
pointer from "walking" when the user lifts the pen and scrolls
repeatedly.
Fixes: https://github.com/linuxwacom/xf86-input-wacom/issues/139
Signed-off-by: Russell Haley <yumpusamongus@gmail.com>
=> Stop pointer movement when panscrolling in relative mode

src/wcmCommon.c, src/wcmUSB.c, src/xf86WacomDefs.h
Fixes #45 
**This is still work in progress**
This patch adds the code to pass on `KEY_PROG1` and friends to the X server, to be passed on to the clients from there. Realistically, this doesn't do anything for the other three codes because they're above the 255 keycode limit and will get dropped by the server immediately.
The handling is hardcoded for the 6 buttons we care about, IMO there's little point to make this a fully generic.
I'm not sure if the events can occur on their own without any `EV_ABS` like we do for the normal buttons. Right now, the code assumes they are not affected by proximity, etc.
cc @jigpu, @Pinglinux, @skomra
=> Pass on the hw button keycodes

src/wcmValidateDevice.c
Devices like the Cintiq Pro 32 have pad devices that have no ExpressKeys.
This prevents them from being recognized as a pad by the driver. When
the device is connected, an `Invalid type 'pad' for this device`
message would be logged.
This has not been an issue in the past since there is nothing for the
device to do without any ExpressKeys. Now that the driver is capable
of forwarding the various softkeys as fixed-function keyboard events,
however, it would be good to ensure that these kinds of devices are
detected properly.
Recognizing the device as a pad only requires us to expand on the list
of tools that are known identifiers. Since we want softkey-only pads to
be recognized, we two softkeys to the list. One or both of the keys
should be present on devices like the Cintiq Pro 32, …
=> Recognize pad devices which only have softkeys (e.g. Cintiq Pro 32)

src/wcmConfig.c, src/wcmValidateDevice.c
Modifies logging done in the hotplug process to prevent the driver from writing a certain set of (non-)errors to the Xorg logfile. These error messages can confuse users who do not realize these specific messages were "normal" and did not indicate an actual error condition.
=> Silence nonerrors

.github/workflows/main.yml, conf/Makefile.am, configure.ac, include/Xwacom.h, man/Makefile.am, man/wacom.man, src/wcmCommon.c, src/wcmConfig.c, src/wcmFilter.c, src/wcmFilter.h, src/wcmISDV4.c, src/wcmTouchFilter.h, src/wcmUSB.c, src/wcmValidateDevice.c, src/wcmXCommand.c, src/xf86Wacom.c, src/xf86Wacom.h, src/xf86WacomDefs.h, test/Makefile.am, test/fake-symbols.c, tools/xsetwacom.c
The first patchset of probably quite a few to come, a few low-hanging fruit.
We bump to xserver 1.10 which is 10y old now and available since RHEL6.2, so safe enough. This gives us `xf86IDrvMsg` which is a more consistent way of logging. The rest is janitorial.
cc @Pinglinux
=> Require xserver 1.10, use xf86IDrvMsg

src/wcmConfig.c, src/wcmISDV4.c, src/wcmUSB.c, src/wcmValidateDevice.c, src/xf86Wacom.c, src/xf86Wacom.h, src/xf86WacomDefs.h, test/fake-symbols.c
Use two standard libc calls instead of their server wrappers and change `wcmOpen()` to have a more sensible behaviour. 
The rest is just tidying up.
=> Miscellaneous janitor patches

configure.ac, meson.build, src/wcmCommon.c, src/wcmTouchFilter.c, src/wcmValidateDevice.c, src/xf86Wacom.c, src/xf86Wacom.h, src/xf86WacomDefs.h, test/fake-symbols.c, test/fake-symbols.h
This sits on top of #194  and #195.
1.13 is 9 years old by now and it's available in RHEL6.4 and later, so we should be good here. Most of the ABI changes happened before that release, so we can drop most of our ifdefs.
=> Require xserver 1.13

src/wcmCommon.c, src/wcmXCommand.c, src/xf86Wacom.c, src/xf86Wacom.h, src/xf86WacomDefs.h
Sits on top of #192 , only the last 3 matter
This simplifies the handling of button actions, instead of copying arrays around we just wrap those into a struct that can be passed around easier.
=> Rework the action handlers

src/wcmCommon.c, src/wcmConfig.c, src/wcmISDV4.c, src/wcmUSB.c, src/wcmValidateDevice.c, src/wcmXCommand.c, src/xf86Wacom.c, src/xf86Wacom.h, src/xf86WacomDefs.h, test/wacom-tests.c
This sits on top of #193 but overall it's just cleanup with no functional changes to the driver.
Notable changes:
- we're down to very few ifdefs now after requiring kernel 2.6.30 and #defining the remaining few
- we now store the input props in the driver too - we only ever check one of those but the few bytes needed won't hurt us
The rest is just cleanup, some functions moved and/or slightly changed to make them easier to follow, some bits no longer needed were dropped, etc.
=> General cleanup with a few odd fixes

meson.build
round() requires linking with -lm
=> meson.build: link libm into the driver

configure.ac
test/../src/common.mk:3: warning: source file '$(top_srcdir)/src/wcmCommon.c' is in a subdirectory,
test/../src/common.mk:3: but option 'subdir-objects' is disabled
test/Makefile.am:2:   'test/../src/common.mk' included from here
etc
=> Enable subdir-objects to stop autotools from complaining

src/wcmConfig.c
Coverity warns that a null dereference of `priv` can be triggered if the
function's call to calloc fails. Take care to verify that `priv` itself
has been allocated before trying to free its members.
=> Fix null dereference warning from Coverity

Makefile.am
Use of single-quotes in the argument to sed was preventing the shell
from recognizing the subshell syntax.
From https://github.com/linuxwacom/xf86-input-wacom/pull/202#issuecomment-992791352
cc @jigpu
=> Correct contents of config-ver.h when using autotools

src/wcmCommon.c
The "throttle" / absolute scrollwheel found on devices like the 4D Mouse
should be reported in the v4 axis. A typo in a previous commit caused
it to stop being reported.
Fixes: 58a931bc21 ("Abstract the event interface to pass a struct with axis data around")
=> Report puck "throttle" (absolute scrollwheel) data in correct axis

.github/workflows/coverity.yml
These always fail since we don't have the required secrets. Skip that
job unless we're on the upstream repository.
=> github: skip the coverity workflow in the forks

.github/workflows/build.yml, src/wcmCommon.c, src/wcmConfig.c, src/x11/xf86Wacom.c, src/x11/xf86WacomProperties.c
=> Fix a compilation error when DEBUG is undefined

meson.build, meson_options.txt
On Ubuntu 20.04 at least, libdir is /usr/lib/x86_64-linux-gnu/ but the
xorg modules are in /usr/lib/xorg/modules/. A default install with
prefix /usr thus puts the modules into the wrong directory.
Fix this by defaulting to the xorg module path from the xserver
pkgconfig file. That has been exported since 2005, so it's save to rely
on.
Fixes #217
=> meson: default to the module dir from xorg-server.pc

.github/workflows/build.yml, src/Makefile.am
Need to add this to `EXTRA_DIST` so an autotools-generated tarball includes the files that aren't used by autotools.
And add a CI job so this is tested for.
=> Fix the new gwacom files missing from the tarball

src/x11/xf86Wacom.c
xf86Post*EventP requires that the valuators array index 0 is whatever
first_valuator is.
Found in #222
cc @Greenscreener
=> x11: handle valuators with a first_valuator != 0 correctly

meson.build
```
NOTICE: Future-deprecated features used:
* 0.56.0: {'Dependency.get_pkgconfig_variable'}
```
=> meson.build: use dep.get_variable() instead of the deprecated one

configure.ac, tools/xsetwacom.c
Because some things we got added to C in the 90s [1] are quite nice to have, or at least not a reason to throw compilation errors.
[1] yes, the 90s. That's how far ahead of the curve we are.
=> autotools: default to C99

src/gwacom/wacom-device.c, src/gwacom/wacom-device.h, tools/wacom-record.c
Structs need to be G_BOXED_TYPE for them to be used through the bindings - otherwise they're just a pointer address that cannot (easily) be used in e.g. python.
And the enums need to follow a specific style, otherwise they're not exported correctly. The names were missing and the enum was interpreted as gpointer, causing wrong alignment.
=> Fix two issues with the gwacom GIR bindings

release.sh
This hasn't been an actual email for ages, the content of this is just
uploaded as release text to github. So let's drop the subject line and
make the rest easier to read.
Fixes #234
=> release.sh: markdown-ify the announce "email"

.github/workflows/build.yml
Otherwise we have the results overwrite each other
=> CI: name the artifacts after the job name/options

configure.ac, meson.build
No longer needed as of ff94040208c9da3411753e1ffe554e6c80b87dd7
=> meson.build: drop the check for -wrap

src/wcmCommon.c
The WacomAxisData calculated by `wcmSendEvents` is expected to contain
the X,Y coordinates which have been adjusted for device rotation and
scale. Prior to the refactoring, the values of X and Y (along with
everything else) were only packaged up for relaying at the very end
of the function. Now this packaging occurs much earlier which requires
our call to `wcmRotateAndScaleCoordinates` to move as well.
Fixes: 58a931bc21d1 (Abstract the event interface to pass a struct with axis data around )
Link: https://github.com/linuxwacom/xf86-input-wacom/issues/226
cc @jigpu, I pulled this out from your branch so we can merge this into 1.0. #241 shows that it's the right fix, so let's go with it :)
Fixes #226
=> Rotate / scale coordinates before storing them in axes

.github/workflows/build.yml
Just to catch any inadvertent reliance on features that came after our
minimum version. Meson *should* warn about this but let's be sure.
Fixes #233
cc @Pinglinux
=> CI: add a job to build with the exact meson version we require

src/wcmCommon.c
The current value needs to be read from the RING2 axis, not the plain
RING axis.
Fixes: 58a931bc21d1 ("Abstract the event interface to pass a struct with axis data around")
=> Correct typo in calculation of relative-mode non-pad RING2 values

configure.ac
Leftover from ad8de30. Because we now only have one thing to check,
let's always check for dl and handle the special "auto" case based on
the outcome of the dl check.
Fixes #248
=> configure.ac: fix the check for unittests

meson.build
Trying to enable this option results in the following configuration
error:
meson.build:117:10: ERROR: Configuration set requires 2 arguments.
=> meson: Fix fuzzinterface build option

.github/workflows/black.yml, .github/workflows/build.yml, meson.build, test/Makefile.am, test/__init__.py, test/conftest.py, test/devices/wacom-pth660.yml, test/test_wacom.py
This adds a python-based test suite (hooked up through pytest) so we can test the driver internals. This won't work for the X11 specific bits but with the gwacom library we can easily test the rest of the driver.
Needed to run locally, for `pytest` to run against meson `builddir`:
```
$ export GI_TYPELIB_PATH="$PWD/builddir:$GI_TYPELIB_PATH"
$ export LD_LIBRARY_PATH="$PWD/builddir:$LD_LIBRARY_PATH"
```
cc @jigpu, an example test for your fix to #226 is included here
edit: `pytest` needs to be run as root since we're going through uinput and are opening event nodes
=> Add a driver test suite through pytest

meson.build
meson has `gnu_symbol_visibility` which is set correctly depending on the
compiler. Except - where the X server was built with a
symbol-visibility-supporting compiler it will always force
`-fvisibility=hidden` into the cflags, see
https://gitlab.freedesktop.org/xorg/xserver/-/issues/1316
Meson sorts pkgconf cflags after the `gnu_symbol_visibility` flag so the
pkgconf cflag overrides our gnu_symbol_visibility flag.
Make a note on this so no-one else has to spend time wondering about and
debugging this.
=> meson: use gnu_symbol_visibility - sort-of

meson.build
These are handled as part of meson's warning_level project option
cc @eli-schwartz, your wish, my command etc. as requested in https://github.com/linuxwacom/xf86-input-wacom/pull/254#discussion_r811531895
=> meson.build: comment out -Wall -Wextra

src/wcmCommon.c, src/x11/xf86WacomProperties.c
The driver's "pan" feature allows you to send scroll events by holding down
a defined stylus button and dragging the pen. Dragging the pen from top
to bottom will cause the driver to send scroll-up events, and vice-versa.
This simulates physically dragging the page under the cursor and works
particularly well with display tablets.
The rate at which scroll events are sent is controlled by comparing the
distance the pen has moved "down" to a defined threshold value. If the
distance exceeds the threshold a scroll-up event is sent; if it exceeds
the the threshold * -1 a scroll-down event is sent.
This commit allows the driver to accept negative threshold values to
produce an inverted scrolling behavior (i.e. dragging the pen from top
to bottom causes scroll-down events instead of scroll-up). …
=> Allow negative panscroll threshold for inverted scrolling

src/WacomInterface.h, src/wcmCommon.c, src/wcmUSB.c, test/Makefile.am, test/__init__.py, test/test_wacom.py, test/wacom-test-env.sh
cc @skomra 
A few useful cleanups, then a few necessary cleanups, and finally the small change to test artpen rotation comes through as expected.
Confusingly, artpen rotation is **not** sent through the rotation axis but through the "wheel" axis. rotation is only for cursor/puck rotation. The artpen physical rotation in `ABS_Z` is handled by the driver as wheel because the X11 valuator is shared with the airbrush wheel.
=> Test artpen rotation

src/wcmConfig.c, test/__init__.py, test/conftest.py
Set an option on all our created uinput devices, and an environment
variable when we're running the test suite. If both of these are set we
process the device, otherwise ignore the device during PreInit.
This stops the driver picking up events from test suite runs
(potentially clicking around on the desktop) and it stops the test suite
from false positives by locally connected devices.
=> test: ignore test devices, or real devices during test suite runs

src/wcmCommon.c, test/__init__.py, test/test_wacom.py
Supersedes #261 
@skomra's patch is identical to #261, only the patch to add the test is different.
Arguably the test should be a separate one but that would require copy/paste of 90% of the test code which is more likely to become an issue than a single condition in the current test that differs based on stylus type, so let's go with that.
=>  Don't report fifth valuator unless it exists on tool (v2)

meson.build, test/__init__.py
use debug logging by default and raise an import error with a better explanation. Maybe that "fixes" #272, cc @Pinglinux
=> Better test suite errors

test/__init__.py, test/conftest.py, test/test_wacom.py
This is a fairly simple edit, but I think it would be very useful, if there was a vim modeline in all the python files too, so at least the indentation doesn't break if one has a custom config.
=> Added vim modelines to python files.

meson.build
At least Ubuntu 20.04 has pytest point at the Python 2.x compatible
version, resulting in syntax errors when trying to parse our Python 3
code files. So let's check pytest-3 first since that is the compatible
version and fall back to normal pytest only where it's missing.
Fixes #272
=> meson: default to pytest-3 first, then pytest

test/__init__.py, test/test_wacom.py
This was slightly too complicated to add to the existing
test_axis_updates test, so that test is duplicated here, only testing
what we see as "wheel" axis in the driver.
The test is run for all three pens
Because the X driver unconditionally sets ds->abswheel from the kernel
events, we must take care only to send the kernel axis that matters for
our current tool - otherwise we overwrite ds->abswheel with whichever
one of ABS_Z or ABS_WHEEL is sent last in the evdev frame.
In other words, we cannot test that artpen ignores ABS_WHEEL and
airbrush ignores ABS_Z because ... they don't.
For the generic pen that doesn't matter since we're supposed to ignore
both axes anyway.
cc @Pinglinux 
The `test_axis_updates` should probably drop the wheel handling now and instead run for the airbrush as-is …
=> test: add a test for the artpen/airbrush wheel updates

src/x11/xf86WacomProperties.c
The function moved away in e4ea35d56aec59a5de0ef3d9282fdd796d89e6ad,
let's drop this comment.
Found by @Greenscreener
=> Remove a comment referring to the wrong function

src/wcmUSB.c
For some devices, such as AES pens, serial number is 0 when tool
comes into proximity. That means serial number was not ready. It
is a known state. All we needed is to wait for the non-zero serial
number. Don't report it through W_ERROR.
Signed-off-by: Ping Cheng <ping.cheng@wacom.com>
=> Don't report error when waiting for serial number

src/wcmTouchFilter.c
Patch [65b7c37](https://github.com/linuxwacom/xf86-input-wacom/commit/65b7c37f0fac5cdd03ff7f977124148d0bdf4be8) fixed spurious right-clicks by setting wcmGestureMode
back to GESTURE_CANCEL_MODE immediately when there is less than two
fingers on the tablet, if the wcmGestureMode was in SCROLL_MODE or
ZOOM_MODE.
However, it narrowed wcmFingerTapToClick() routine to LAG_MODE, which
removed the opportunity for the routine to be executed. Revert that.
The issue was reported by https://github.com/linuxwacom/xf86-input-wacom/issues/103
Fixes: [65b7c37](https://github.com/linuxwacom/xf86-input-wacom/commit/65b7c37f0fac5cdd03ff7f977124148d0bdf4be8)
(Prevent spurious right-clicks at the end of very short scroll and zoom gestures)
Signed-off-by: Ping Cheng <ping.cheng@wacom.com>
=> Bring two finger right-click function back

src/wcmCommon.c
Copy/paste error from when this as lifted from the properties code to
the core driver code, in the commits leading up to
5326fd126042684338dfb662f48ba2e27be7fa5a.
=> Remove useless Wacom action name setting

src/x11/xf86Wacom.c
Let's add a helper function for this so we can't mess this up.
Somewhat related to #222 since this adds new axes.
cc @Pinglinux, @jigpu, @Greenscreener
=> x11: de-duplicate the valuator number assignment

src/gwacom/wacom-device.c, src/gwacom/wacom-device.h
This is a hack to make it possible to test options that cannot be set
through the xorg.conf, e.g button actions that are set through the
X-specific properties interface.
Expose a new function for "runtime options", though the actual option
implementation needs to be handled in the gwacom wrapper code - i.e.
only options explicitly supported can work.
The currently supported option is "PanButton" which maps the given
button to the PanScroll action.
See https://github.com/linuxwacom/xf86-input-wacom/pull/222#issuecomment-1193299467
=> gwacom: add support for special runtime options

src/gwacom/wacom-device.c, src/wcmConfig.c, src/x11/xf86Wacom.c, src/xf86WacomDefs.h
ValuatorMask has been around since xserver 1.10, released in 2011.
This is extracted from #222 with a minor whitespace fix and a merge conflict fixed, courtesy of 8e4a77bc28970d23da80838c195550cad4ef8e05
cc @Greenscreener
=> Replace valuator array with valuator mask in convertAxes

.github/workflows/black.yml, .github/workflows/build.yml, .github/workflows/coverity.yml
Node 12 is deprecated so let's switch to the newer version 
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> CI: update some actions to v3

man/wacom.man
All our options were indented by an extra 4 units, unnecessary since we use TP for all of those anyway and get a highlight.
=> man: remove some unnecessary indent

release.sh
Leftover from the xorg release.sh script, no longer needed here since we only ever release one module at a time.
=> release.sh: drop support for modfiles and module sets

man/wacom.man, src/wcmCommon.c, src/wcmConfig.c, src/wcmValidateDevice.c, src/x11/xf86Wacom.c, src/xf86WacomDefs.h, test/test_wacom.py
This is a backwards-compatibility option similar to the Pressure2K
option. GDK2 applications are effectively limited to 7 axes
(value of GDK_AXES_LAST in GDK2) and adding smooth panscrolling gives
our device 8 axes total. This can cause issues when the driver, GDK and
the application don't agree on the number of axes in the device.
This is an application/GDK bug but as for the Pressure2K option we
expect there to be applications that cannot be updated easily. To work
around this, provide a driver option to disable this new feature
altogether and effectively return to 6 axes for the pen device.
This is a partial revert of https://github.com/linuxwacom/xf86-input-wacom/commit/fe923e927a8ddf4d2e82ef4757c885b06d47fa03 "Implement smooth panscrolling"
for the implementation. Minor changes …
=> Add option SmoothPanscrollingEnabled

meson.build, src/common.mk, src/wcmFilter.c, src/wcmPressureCurve.c, src/wcmPressureCurve.h, tools/Makefile.am, tools/pressurecurve.c
This tool takes (one or multiple) sets of 4 coordinate that represent
the second and third point for our pressure curve (first and fourth
points are hardcoded to 0/0 and 1/1 like the driver does)
It spits out gnuplot-compatible lines that can be printed for visual
debugging. Usage to print the GNOME default curves:
```
./pressurecurve \
0 .75 .25 1 \
0 .5 .5 1  \
0 .25 .75 1 \
0 0 1 1 \
.25 0 1 .75 \
.5 0 1 .5 \
.75 0 1 .25 > gnuplot.data
```
And that gnuplot data can then be printed with:
```
#!/usr/bin/gnuplot
set terminal qt persist
set style data lines
set xrange [0:1]
set yrange [0:1]
plot \
"gnuplot.data" using 1:2 title "  0, .75, .25, 1", \
"gnuplot.data" using 1:3 title "  0, .50, .50, 1", \
"gnuplot.data" using 1:4 title "  0, .25, .75, 1", \
"gnuplot.data" using 1:5 title "  0, …
```
=> Add a tool for pressurecurve debugging

.github/workflows/black.yml, .github/workflows/build.yml, .github/workflows/coverity.yml
Jobs that use the GITHUB_TOKEN to perform sensitive actions on behalf of a real user may be granted a range of permissions. Instead of granting blanket permissions to read and write "all" APIs, we should really limit the permissions what any individual workflow or job can do.
This commit sets the default permissions for each workflow to "contents: read", which allows jobs to only read from the repository.
Link: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idpermissions
=> github: Minimize permissions granted to automated workflows / jobs

src/wcmUSB.c
Automated test runs have detected the following issue while running UBSan checks:
~~~
../src/wcmUSB.c:1372:11: runtime error: left shift of 1 by 31 places cannot
be represented in type 'int'
#0 0x7f0444bcbd8c in mod_buttons ../src/wcmUSB.c:1372
#1 0x7f0444bd7f26 in test_mod_buttons ../src/wcmUSB.c:2090
#2 0x7f0444bfcea7 in wcm_run_tests ../test/wacom-test-suite.c:46
#3 0x56204d77b405 in main ../test/wacom-tests.c:44
#4 0x7f0448625082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)
#5 0x56204d77b1cd in _start (/home/runner/work/xf86-input-wacom/xf86-input-wacom/builddir/wacom-tests+0x11cd)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/wcmUSB.c:1372:11 in
~~~
While the faulty line has some protection against an excessively-large value of 'btn', the bounds are …
=> wcmUSB: Correct bounds check of maximum button number

src/wcmUSB.c
This fixes #329 which fixed the undefined behavior but that was caused by the wrong type. cc @jigpu
=> wcmUSB: fix undefined behavior for bit-shifting 

meson.build, meson_options.txt
xsetwacom pulls in the xorgproto and Xlib dependencies, so let's make this optional for the (niche) case of where we really only want the driver built.
Since this is a rather niche case let's make it a boolean true/false option instead of a feature with "auto".
---
Currently working on an Xserver CI pipeline that also builds the drivers to make sure we don't fail that so keeping this on in draft until we have that in place.
See https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/1318
=> meson.build: allow disabling the xsetwacom build

release.sh
Apparently the old way no longer works, so let's update with a copy/paste from the examples.
Intentional switch to use --token because that's how you should be doing releases anyway - with a temporary token that can be revoked after the release is complete (and that also encodes the username).
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release
=> release.sh: update to take a --token value

release.sh
two cleanups and one simplification: we don't need to enforce the extra dot for the module: `release.sh  .`. We only ever use this script on one repo anyway, so let's imply that.
=> release script simplifications

src/wcmConfig.c
wcmForeachDevice returns 0 for no matches, a negative errno or the greater-than-zero number of matches. In wcmMatchDevice we return either 0 or 1 as matchDevice() stops the foreach once the first match is encountered.
Fixes: d5ca999f35c7 ("Add a helper function to iterate over local devices to the driver layer") Closes #342
cc @omcaif
=> Fix wcmForeachDevice check in wcmMatchDevice

man/wacom.man
Since xorg fully started to rely on hotplugging over decade, modern tablet devices can be automatically detected. This commit removes "Section InputDevice" related texts, which is used when hotplugging is disabled.
This changed is related to the issue #339.
=> man: remove texts related to InputDevice

man/xsetwacom.man
ResetArea is an option already available in xf86-input-wacom. And it is the reciprocal option to Area option.
This change adds a description to let users know that xsetwacom has ResetArea to set a tablet back to its default values.
=> man: add the description for ResetArea option

conf/70-wacom.conf
These tablets are supported provided the right kernel driver is loaded, so let's add them by default instead of requiring every user to write a config snippet .
=> conf: add huion and xp-pen to our default snippet

man/xsetwacom.man, src/wcmCommon.c, src/wcmUSB.c, tools/xsetwacom.c
This pull request provides fixes for a few things that I had noticed while working on another set of patches.
=> Miscelaneous fixups

include/wacom-properties.h, man/xsetwacom.man, src/wcmCommon.c, src/wcmConfig.c, src/wcmUSB.c, src/x11/xf86WacomProperties.c, src/xf86WacomDefs.h, tools/xsetwacom.c
The X driver currently has support for devices with a single relative wheel (e.g. scroll wheels on pucks or pads). This patch set adds support for devices that have a second relative wheel sending REL_HWHEEL events from the kernel. Such a control will produce horizontal scrolling events by default. The xsetwacom tool has been updated to allow configuring these controls via the traditional "RelWheel[2]<Up|Down>" commands, as well as a new set of "Dial[2]<CCW|CW>" commands that place relative wheels on the pad (e.g. recent Huion / XP-Pen devices).
=> Add support for multiple relative wheels

conf/70-wacom.conf
Historically we've only bound to Wacom devices and a select few other tablets that were handled by this driver. This required adding those tablets which we forgot for years for e.g. Huion/XP-Pen devices (see commit 4e1d6d61).
At this point we should support pretty much anything that is a tablet so let's bind to those by default.
Exceptions for Wacom touchpad/touchscreens stay in the file and so do some other ones that are too hard to test whether they're handled by them generic MatchIsTablet condition.
Closes #353
=> conf: bind this driver to all tablets by default

man/wacom.man
=> man: discourage use of Section InputDevice

meson.build
=> meson.build: fix variable name when dealing with systemd-unit-dir
